name: CI/CD Monorepo Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: true  # Automatically runs pnpm install at root

      - name: Confirm directory structure
        run: ls -la && ls client && ls server

      - name: Build backend (optional)
        run: |
          cd server
          pnpm run build || echo "No backend build step defined"

      - name: Build frontend
        run: |
          cd gis-mapping-client
          pnpm run build
