name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'

      # 👉 Backend
      - name: Install backend dependencies
        working-directory: server
        run: pnpm install

      - name: Build backend
        working-directory: server
        run: pnpm run build || echo "No build script defined"

      - name: Deploy backend to Render
        run: curl -X POST "$RENDER_DEPLOY_HOOK"
        env:
          RENDER_DEPLOY_HOOK: ${{ secrets.RENDER_DEPLOY_HOOK }}

      # 👉 Frontend
      - name: Install frontend dependencies
        working-directory: gis-mapping-app
        run: pnpm install

      - name: Build frontend
        working-directory: gis-mapping-app
        run: pnpm run build

